# Generated by Django 5.0 on 2024-01-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodorotimer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('work_duration', models.IntegerField(default=25)),
                ('break_duration', models.IntegerField(default=5)),
                ('intervals', models.IntegerField(default=4)),
                ('is_break', models.BooleanField(default=False)),
            ],
        ),
    ]
