# Generated by Django 5.0 on 2024-01-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodorotimer', '0002_timer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model',
        ),
    ]
