# Generated by Django 5.0 on 2024-01-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodorotimer', '0003_delete_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timer',
            name='is_break',
        ),
        migrations.RemoveField(
            model_name='timer',
            name='start_time',
        ),
    ]
